- name: Встановити програми за допомогою Chocolatey
  hosts: windows
  become: yes

  tasks:
    - name: Встановити Google Chrome
      win_chocolatey:
        name: googlechrome
        state: present
    
    - name: Встановити Visual Studio Code
      win_chocolatey:
        name: visualstudiocode
        state: present
    
    - name: Встановити VLC media player
      win_chocolatey:
        name: vlc
        state: present
    
    - name: Встановити 7-Zip
      win_chocolatey:
        name: 7zip
        state: present
    
    - name: Встановити Node.js
      win_chocolatey:
        name: nodejs
        state: present

