---
- name: Install Archive Manager
  hosts: all
  become: yes

  tasks:
  - name: Install Archive Manager on Ubuntu
    when: ansible_os_family == 'Debian'
    apt:
      name: file-roller
      state: present

  - name: Install Archive Manager on CentOS
    when: ansible_os_family == 'RedHat'
    yum:
      name: file-roller
      state: present

  - name: Install 7-Zip on Windows
    win_chocolatey:
      name: 7zip
      state: present

